FROM ubuntu

RUN apt-get update && \
        apt-get install -y --no-install-recommends \
        openssh-client \
        openssh-server \
        rsync && \
        mkdir -p /var/run/sshd && \
        mkdir -p /root/.ssh

RUN apt-get update && \
        apt-get install -y --no-install-recommends python3-hvac

COPY sshd_config /etc/ssh/sshd_config

VOLUME /run/privateer
VOLUME /privateer
EXPOSE 22

ENTRYPOINT ["/usr/sbin/sshd", "-D", "-E", "/dev/stderr"]
