FROM ubuntu

RUN apt-get update && \
        apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        openssh-client \
        rsync && \
        mkdir -p /root/.ssh

RUN curl -L -o /usr/bin/yacron https://github.com/gjcarneiro/yacron/releases/download/0.19.0/yacron-0.19.0-x86_64-unknown-linux-gnu && \
        chmod 755 /usr/bin/yacron

COPY ssh_config /etc/ssh/ssh_config
VOLUME /privateer/keys
