FROM ubuntu

RUN apt-get update && \
        apt-get install -y --no-install-recommends \
        openssh-client \
        rsync && \
        mkdir -p /root/.ssh

COPY ssh_config /etc/ssh/ssh_config
VOLUME /run/privateer
